### ISSUE TITLE
Add ERC20 Transfer Event Along With Redemption/Issue Events

### ISSUE THREAD

**Issue by bonedaddy** [verified-network/via-issuer#27]
As the transfers are happening without emittion of the ERC20 `Transfer` event, public block explorers dont display token transfers. This should fix [transactions like this one](https://ropsten.etherscan.io/tx/0x32aa413e8f697d863037ea67baf181f2fc142347564f3443a9d3c646f368b6f0) not displaying token issuance.

**Comment by kallolborah** [comment]
I am doing the transfer functions in both cash and bond contracts. The placement of emit functions is not very obvious, so am doing it to save effort.

**Comment by bonedaddy** [comment]
Closed by https://github.com/verified-network/via-issuer/pull/28
