### ISSUE TITLE
Change from call to transfer

### ISSUE THREAD

**Issue by kallolborah** [verified-network/via-issuer#31]
How do we change from call to transfer [here](https://github.com/verified-network/via-issuer/blob/transfers/contracts/Cash.sol#L374) and [here](https://github.com/verified-network/via-issuer/blob/transfers/contracts/Cash.sol#L394) ?

Transfer might be more appropriate and safer from what I have read.

**Comment by kallolborah** [comment]
Similar call.value calls are also there in bond.sol, please check

**Comment by bonedaddy** [comment]
These are all the ones I need to change:

* https://github.com/verified-network/via-issuer/blob/master/contracts/Bond.sol#L280
* https://github.com/verified-network/via-issuer/blob/master/contracts/Bond.sol#L309
* https://github.com/verified-network/via-issuer/blob/master/contracts/Bond.sol#L394
* https://github.com/verified-network/via-issuer/blob/master/contracts/Bond.sol#L399
* https://github.com/verified-network/via-issuer/blob/master/contracts/Cash.sol#L367
* https://github.com/verified-network/via-issuer/blob/master/contracts/Cash.sol#L385
