### ISSUE TITLE
Oracle calls 

### ISSUE THREAD

**Issue by kallolborah** [verified-network/via-issuer#32]
I checked calls made from viaoracle.sol are reaching azure and responses are returned, not sure why callbacks fail to happen from viaoracle.sol - I suspect something is wrong with the viaoracle’s callback function.

**Comment by bonedaddy** [comment]
# Rinkeby Contracts


```
Token address: 0x8c54A59e97521Dff7323A39F4DdcF3d9849415f6
Token name: Via_USD
Token type: ViaCash

Token address: 0x5Cad3D39A6854c2d90cF3A9c9faB373AEBE817f4
Token name: Via_EUR
Token type: ViaCash

Token address: 0x049680079f3a7fec394f8c4217cEc668Ae0Bf4b1
Token name: Via_INR
Token type: ViaCash

Token address: 0x4A8Ded4db1824D1161238B01BF7FE15C31b9A35B
Token name: Via_USD
Token type: ViaBond

Token address: 0x547187d93b76Df5777ed03e539461bd523c764C4
Token name: Via_EUR
Token type: ViaBond

Token address: 0xd946e713c7a890cDE5d88a1E5cA6E5EBc31ff849
Token name: Via_INR
Token type: ViaBond
```


Factory: 0xD12C63a6B1942AE27D692c1F967e65138B057650

Token: 0x9D904b14364C541591573B93c5836710155C0dC2

Bond: 0xbA513Ce6aAddAEA68aDE70a0de22437584c8dCFD

Cash: 0x39Ed9cbC8a419D3cEAc320f143FAB6E5a5A11498

ViaOracle: 0xc97BE8877F48E975680BC6c5C959931E08ba2f88

**Comment by kallolborah** [comment]
Line 313 in the cash contract is a check for empty values coming back from oracle. I have added a event in line 315. We should check if this event is triggered for the via-Eur test case.

**Comment by kallolborah** [comment]
The ‘oracle’ branch is WIP. However, I found a few problems that explain why callbacks were not happening

1. In the via-Eur test case, the address to which ether was being sent was actually via-usd. That is why one call was made. That was a bug in the test case. Now, correct number of calls are happening.

2. Reason the via oracle was sending back empty response is probably because the oracle was not specifying the app/json in the response header. I fixed it. Need to test.

3. Third issue is that in test cases when there are two callbacks, we should subscribe to two events. This was not happening in the via-Eur case. Fixed it.

4. I also observed that string(abi.encodePacked(...)) in line 91 of the via oracle which we have used to create the via oracle query is appending a whole bunch of 0s in the end. I am not sure if this leads to a failure in making the call itself. I couldn’t see calls in azure and that is why I hardcoded the currency in line 92. Need to test this. But if trailing zeros are a problem, we need a way to trim them before the via oracle call is made.

——-
For the time being, please check out the oracle branch from GitHub to test. I will update it tomorrow after checking all the test cases in cash and bond.

**Comment by bonedaddy** [comment]
> The ‘oracle’ branch is WIP. However, I found a few problems that explain why callbacks were not happening
> 
>     1. In the via-Eur test case, the address to which ether was being sent was actually via-usd. That is why one call was made. That was a bug in the test case. Now, correct number of calls are happening.
> 
>     2. Reason the via oracle was sending back empty response is probably because the oracle was not specifying the app/json in the response header. I fixed it. Need to test.
> 
>     3. Third issue is that in test cases when there are two callbacks, we should subscribe to two events. This was not happening in the via-Eur case. Fixed it.
> 
>     4. I also observed that string(abi.encodePacked(...)) in line 91 of the via oracle which we have used to create the via oracle query is appending a whole bunch of 0s in the end. I am not sure if this leads to a failure in making the call itself. I couldn’t see calls in azure and that is why I hardcoded the currency in line 92. Need to test this. But if trailing zeros are a problem, we need a way to trim them before the via oracle call is made.
> 
> 
> ——-
> For the time being, please check out the oracle branch from GitHub to test. I will update it tomorrow after checking all the test cases in cash and bond.

I tried the tests using ganache and etheruem-bridge, and the `LogResult` events are now being emitted. I did however encounter this test failure

```
  1) Contract: IssuingViaEUR
       should send ether to Via-EUR cash contract and then get some Via-EUR cash tokens:
     Error: Timeout of 300000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/media/solidity/DATA/Code/via-issuer/test/ViaCash.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```

**Comment by kallolborah** [comment]
I can see that rinkeby callbacks get the correct values now. Did you get any via-Eur tokens generated ?

But I am struggling with the test javascript code on how we can control the promise code - we need to be able to create a promise that listens to both callbacks and then return. Can you also check in the oracle branch ?

**Comment by kallolborah** [comment]
I chained promises In the via-usd and via-Eur test cases but then realised its probably not necessary. Can you try to resolve the issue ? It’s much easier and faster to test the contracts using these test cases.

**Comment by kallolborah** [comment]
@bonedaddy the latest push to the oracle branch is passing 15 out of 18 tests. I had to bypass the oracle to get around the issue of callbacks not getting captured by cash and bond testjs. But I think callbacks are working - can you recheck callbacks on rinkeby using your branch ? Just ping the viaoracle url in browser so that the database wakes up before the oracle is used from the contracts. If you can see both callbacks in the via-Eur case, we can be sure that the bug is in the testjs files for cash and bond.

**Comment by bonedaddy** [comment]
Yes I will test it now

**Comment by bonedaddy** [comment]
I tried on rinkeby using my branch and got two callbacks, however one of the callbacks included an empty result.

* https://rinkeby.etherscan.io/tx/0x9227730a72b9e746b493e63db49a1a0607433fff5afe3244b09ad42e511beda5
* https://rinkeby.etherscan.io/tx/0x4e9c54c54bf656bb9d36728ff4559a831667f4d339b98268265c2b38ea6bb074

**Comment by kallolborah** [comment]
@bonedaddy can you replace the following block of code in viaoracle.sol and try again ? I have simply hardcoded the viaoracle here. Before testing, it’s also important to ping the hard coded url on browser a couple of times to make sure the database connection is up and a value is returned.

url if(_ratetype == "er" || _ratetype == "ver"){
                //bytes32 queryId = provable_query("URL", string(abi.encodePacked("json(https://via-oracle.azurewebsites.net/rates/er/",_currency,").rate")),CUSTOM_GASLIMIT);  
                bytes32 queryId = provable_query("URL", "json(https://via-oracle.azurewebsites.net/rates/er/Via_USD_to_Via_EUR).rate",CUSTOM_GASLIMIT);
                pendingQueries[queryId] = params(_tokenContract, _tokenType, _ratetype);
                emit LogNewProvableQuery(string(abi.encodePacked("Provable query was sent for Via exchange rates for ",_currency)));
                return queryId;
            }

**Comment by bonedaddy** [comment]
Sure I'll try that again

**Comment by bonedaddy** [comment]
@kallolborah great work on the debugging, i finally got the oraclize callback to include results both times.

* https://rinkeby.etherscan.io/tx/0xc3294d23fb2ac51f316e6901fe51818257b55e44f751357d9c982facb38ad22b
* https://rinkeby.etherscan.io/tx/0x6efa3f97f0e2a23e3b548055e7479a617a84df17be08fa6b0b6072ad35e34371

**Comment by kallolborah** [comment]
@bonedaddy thanks for testing this, so this means the string packing we have blocked out has a bug - can you find a fix ? I will finish off cash and bond contract reviews and tests (by passing the oracle since that makes life easy) today hopefully and then tomorrow, we can test the contracts with the oracle.

**Comment by bonedaddy** [comment]
Yup I'll take a look at it

**Comment by bonedaddy** [comment]
I made a modification to decode the `_currency` parameter from `bytes32` to `string`, logging the result, and using that when constructing the URL to send to oraclize. [See here](https://github.com/verified-network/via-issuer/blob/fix%23oracle/contracts/oraclize/ViaOracle.sol#L91-L92).

I deployed this to rinkeby, and sent ETH to the via eur contract [with this transaction](https://rinkeby.etherscan.io/tx/0x3e9b36cbf4813b8e32ab9ac56dba20a2ea790e216ba3e7c0e96aed2ebbbc039e#eventlog). The following screenshot shows the new transaction emitted which includes the currency, note that it says `eth`.


![event](https://user-images.githubusercontent.com/17089485/99589911-8ffdf680-29e4-11eb-9774-fccedfa9ee4d.png)


Given how we [construct the URL to send a request to oraclize](https://github.com/verified-network/via-issuer/blob/fix%23oracle/contracts/oraclize/ViaOracle.sol#L94) (`json(https://via-oracle.azurewebsites.net/rates/er/",currency,")`), it seems that the URL oraclize would be request is `https://via-oracle.azurewebsites.net/rates/er/eth` which would explain why we are getting an empty result being submitted in the callback, as I believe this is an incorrect url.

**Comment by kallolborah** [comment]
@bonedaddy currency can be ‘eth’ if ratetype is ‘ethusd’. Can you move line 91 and 92 after line 93, 99 and 106 - basically move your check inside the blocks and test again ?

**Comment by bonedaddy** [comment]
sure
