### ISSUE TITLE
Pausable contracts

### ISSUE THREAD

**Issue by kallolborah** [verified-network/via-issuer#39]
Need to make cash and bond pausable.

**Comment by bonedaddy** [comment]
What functions of cash and bond need to be pausable?

**Comment by kallolborah** [comment]
TransferFrom functions in both cash and bond are used for issuing and redemption. These need to be pausable. Also, the fallback functions that accept ether, or alternatively the issue() functions in both cash and bond contracts that the fallback functions call.

**Comment by bonedaddy** [comment]
Sounds good. With regards to fallback functions, I'll put the pausable check into the `issue` function since fallback functions can only use a certain amount of gas.
