### ISSUE TITLE
Websocket and HTTP provider 

### ISSUE THREAD

**Issue by kallolborah** [verified-network/via-issuer#42]
Running the tests with ganache-cli and ethereum-bridge, I faced issues with an error that prints ‘connection not open on send()’.

Thinking this meant the web socket connection was not working, I made websockets = false in truffleconfig.js but got the error - current provider doesn’t support subscriptions - Httpprovider’

Then I uninstalled WS and got the exception that prints - ‘can not connect to node on WS’.

I am using 
- truffle 5.1.53 (latest release)
- node 12.38 
- WS 7.4

**Comment by bonedaddy** [comment]
Can you provide terminal output from when this happened?

**Comment by kallolborah** [comment]
I have found the issue but I am still stuck.
When we run tests, some of our tests use http provider and some use websocketprovider. The providers are in ganache-core. The websocketprovider is required to listen (subscribe) to events like oracle callbacks which the httpprovider in web3 doesn’t support. 

The problem i started facing all of a sudden is - the websocketprovider throws a ‘can not connect to node on WS’. I updated ganache-core, ganache-cli but the issue remains.

**Comment by kallolborah** [comment]
The versions I have are
- ganache-cli 6.12.1
- ganache-core 2.13.1
- node 12.18.4
- truffle 5.1.53
- web3 1.2.9
- ethereum-bridge 6.2 

Can you confirm which versions you have that are working ?

**Comment by bonedaddy** [comment]
* ganache-cli v6.12.1
* ganache-core 2.13.1
* node v12.18.2
* truffle v5.1.51
* web3 1.2.9
* ethereum bridge 6.2

**Comment by kallolborah** [comment]
Closing since this seems like a local machine issue
