### ISSUE TITLE
Support for ETH compatible chain?

### ISSUE THREAD

**Issue by akhekade** [verified-network/via-issuer#54]
Hi,
  I stumbled upon this project. Looks interesting. Is the project live to test?

  Is the team active? Would you consider deploying this on a ETH compatible DPOS chain?

**Comment by kallolborah** [comment]
@akhekade yes, this project is very much active. Where do you want to exactly deploy ?

**Comment by akhekade** [comment]
https://xinfin.network/

https://coinmarketcap.com/currencies/xinfin-network/markets/

RPC: https://rpc.xinfin.network/

Addresses have prefix "xdc" instead of "0x" on eth

no change in tx hashes

https://xdc.network/home

Remix : https://remix.xinfin.network/

Happy to talk commercials for long term support and adoption. 
https://www.linkedin.com/in/atul-khekade-9076b36/

**Comment by kallolborah** [comment]
@akhekade not interested right now
