### ISSUE TITLE
Use SPDX License Identifier at the begining of each solidity source file

### ISSUE THREAD

**Issue by Hsiang-xxs** [verified-network/via-issuer#6]
In the version 0.6.10, Solidity introduces the SPDX License Identifier, that we sould follow.

> ###  **SPDX License Identifier**
>Trust in smart contract can be better established if their source code is available. Since making source code available always touches on legal problems with regards to copyright, the Solidity compiler encouranges the use of machine-readable [SPDX license identifiers]. Every source file should start with a comment indicating its license:
> 
> // SPDX-License-Identifier: MIT
> 
> The compiler does not validate that the license is part of the [list allowed by SPDX], but it does include the supplied string in the [bytecode metadata].
> 
> If you do not want to specify a license or if the source code is not open-source, please use the special value **UNLICENSED**.
> 
> Supplying this comment of course does not free you from other obligations related to licensing like having to mention a specific license header in each source file or the original copyright holder.
> 
> The comment is recognized by the compiler anywhere in the file at the file level, but it is recommended to put it at the top of the file.
> 
> More information about how to use SPDX license identifiers can be found at the [SPDX website].

[SPDX license identifiers]: https://spdx.dev/
[list allowed by SPDX]: https://spdx.org/licenses/
[bytecode metadata]: https://solidity.readthedocs.io/en/v0.6.11/metadata
[SPDX website]: https://spdx.org/ids-how

**Comment by kallolborah** [comment]
Done
